### ISSUE TITLE
Setup Angular2 & TypeScript in a ASP.​NET Core project using Visual Studio

### ISSUE THREAD

**Issue by JuergenGutsch** [JuergenGutsch/blog-issue-test#37]
http://asp.net-hacker.rocks/2016/08/08/setup-angular2-typescript-aspnetcore-in-visualstudio.html

**Comment by JuergenGutsch** [comment]
Comment written by Vahid N. at 08.08.2016 09:38:07:

<p>One day you will need to add routing and server side services and at that time, <br><a href="https://www.nuget.org/packages/Microsoft.AspNetCore.SpaServices/" rel="nofollow noopener" title="https://www.nuget.org/packages/Microsoft.AspNetCore.SpaServices/">https://www.nuget.org/packa...</a><br>can help to provide a fallback <br>routes.MapSpaFallbackRoute("spa-fallback", new { controller = "Home", action = "Index" });</p>

**Comment by JuergenGutsch** [comment]
Comment written by Jürgen Gutsch at 08.08.2016 09:53:27:

<p>Hi Vahid, <br>Many thanks for that hint. Will have a deeper look into that package :)<br>At the first glimpse, this just seems to be needed, if you use all the MVC stuff too. I don't us it, if I create a SPA.</p>

**Comment by JuergenGutsch** [comment]
Comment written by Hector Miguel Asiain Palomo at 08.08.2016 21:46:05:

<p>Hello, regarding this: " [..] but VS shows a yellow exclemation mark because of any arror. Until yet, I didn't figure out what is going wrong here." The package generating the conflict is lite-server, or better said a dependency of it. I unistall it and the yellow mark is gone, I won't be using it anyway at this point.</p>

**Comment by JuergenGutsch** [comment]
Comment written by Jürgen Gutsch at 09.08.2016 08:00:05:

<p>Hello Hector, many thanks for that hint. I'll try to remove it too and update that post.</p>

**Comment by JuergenGutsch** [comment]
Comment written by Hector Miguel Asiain Palomo at 10.08.2016 19:06:51:

<p>We are not alone on this, more info about the issue:<br><a href="https://github.com/aspnet/Tooling/issues/479" rel="nofollow noopener" title="https://github.com/aspnet/Tooling/issues/479">https://github.com/aspnet/T...</a><br>BTW it is a really good post, very useful, thanks.</p>

**Comment by JuergenGutsch** [comment]
Comment written by Jürgen Gutsch at 10.08.2016 20:53:18:

<p>Thanks. Will follow the discussion on that issue :)<br>Glad you like that post.<br>BTW I need to approve comments with links in it. That's why it wasn't shown.</p>

**Comment by JuergenGutsch** [comment]
Comment written by MV10 at 11.08.2016 00:04:07:

<p>This is easily one of the most clearly-written, clean, and straight-to-the-point examples of adding basline Angular2 into a VS2015 .NET Core project. I especially like your no-nonsense gulp script (there are some truly bad ones out there just to move all those files to wwwroot).</p><p>One thing you might want to clarify -- there should be an "app" folder added to the wwwroot folder (I think?), and this is where the main.ts and app.component.ts files go. Took me a few build attempts to sort that out. In my project, at least, there was no app folder initially.</p><p>I'm actually trying to retrofit a basic admin interface into an existing Core API project. After following these instructions, the Angular part isn't working yet. I get a series of TS2304 errors -- Cannot find name Promise, Map, MapConstructor, SetConstructor, and Set. However, es6-promise does show up in the npm Dependencies folder (and I'm running Chrome which shouldn't need it).</p><p></p>

**Comment by JuergenGutsch** [comment]
Comment written by MV10 at 11.08.2016 00:35:21:

<p>Well that didn't take long. The build is fixed thanks to <a href="http://stackoverflow.com/a/36323136/152997" rel="nofollow noopener" title="http://stackoverflow.com/a/36323136/152997">http://stackoverflow.com/a/...</a> ... The tsconfig.json should reference ES6, not ES5. (35 years of programming and we're back to spaghetti code. SMH.)</p><p>One more recommendation -- specify where to put systemjs.config.js. As written (based on index.html) it goes in wwwroot. Personally I think it belongs in app or maybe a scripts folder though.</p><p>There are also typos in systemsjs.config.js -- it specifies "lib" whereas your gulp copies the files to "libs" (plural).</p><p>On top of that I'm getting a lot of 404s trying to read various files from the libs folder.</p><p>At first @angular stuff wasn't coming through. I changed "@angular":"libs/@angular" in the systemjs.config.js since I noticed gulp didn't reproduce the top @angular folder and it cleared those up, but then I started getting 404s on rxjs.</p><p>I don't really know gulp yet but it looks like the correct folder hierarchy isn't being reproduced. I'd definitely like to see the fix for this because, as I noted, your gulp file is pretty clean compared to the hack jobs I see posted in most places elsewhere.</p><p>Edit: Thought we needed to add { base: 'node_modules' } after the src list, but that just causes other errors when things like "reflect.js" are referenced from libs instead of their origin folder in node_modules. I assume there must be a standard way of dealing with this but it's beyond me right now...</p><p>Overall still pretty happy with this though.</p>

**Comment by JuergenGutsch** [comment]
Comment written by MV10 at 11.08.2016 01:04:11:

<p>The fix for the other 404s is related to the corrected folder structure (well, "complete" folder structure, I don't know if it's correct as per The Angular Way)... the polyfill section in index.html needs to change to:</p><p>    &lt;script src="libs/core-js/client/shim.min.js"&gt;&lt;/script&gt;<br>    &lt;script src="libs/zone.js/dist/zone.js"&gt;&lt;/script&gt;<br>    &lt;script src="libs/reflect-metadata/reflect.js"&gt;&lt;/script&gt;<br>    &lt;script src="libs/systemjs/dist/system.src.js"&gt;&lt;/script&gt;</p><p>And with that, it runs under VS2015 Update 3 with .NET Core 1.0 release and Angular2 RC5.</p><p>(Edit -- note this references an earlier comment that is awaiting moderation, I guess probably because I included a stackoverflow link.)</p>

**Comment by JuergenGutsch** [comment]
Comment written by Jürgen Gutsch at 11.08.2016 07:39:26:

<p>Hi, <br>many thanks for all of your comments. :) <br>I'll update this post in the next days to to be more clear in some points and to fix some possible errors. I think I also need to update this post to Angular RC5. <br>Unfortunately they changed a lot while the product is RC (same mistake as Microsoft did with ASP.NET Core from RC1 to RC2) and they will change a lot more until release<br><a href="http://angularjs.blogspot.ch/2016/08/angular-2-rc5-ngmodules-lazy-loading.html" rel="nofollow noopener" title="http://angularjs.blogspot.ch/2016/08/angular-2-rc5-ngmodules-lazy-loading.html">http://angularjs.blogspot.c...</a></p>

**Comment by JuergenGutsch** [comment]
Comment written by Rodrigo Basniak at 13.08.2016 15:06:37:

<p>Hi, I tried to follow your steps but when running the npm install I get the following output on the output window:</p><p>PATH=.\node_modules\.bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External;%PATH%;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\git<br>"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\npm.CMD" install<br>npm WARN install Couldn't install optional dependency: Unsupported<br>&gt; dotnetpro-ecollector@1.0.0 postinstall C:\Users\rbasniak\Documents\Visual Studio 2015\Projects\WebApplication4\src\WebApplication4<br>&gt; typings install &amp;&amp; gulp restore<br>module.js:327<br>    throw err;<br>    ^<br>Error: Cannot find module 'popsicle'<br>    at Function.Module._resolveFilename (module.js:325:15)<br>    at Function.Module._load (module.js:276:25)<br>    at Module.require (module.js:353:17)<br>    at require (internal/module.js:12:17)<br>    at Object.&lt;anonymous&gt; (C:\Users\rbasniak\Documents\Visual Studio 2015\Projects\WebApplication4\src\WebApplication4\node_modules\popsicle-retry\dist\index.js:4:18)<br>    at Module._compile (module.js:397:26)<br>    at Object.Module._extensions..js (module.js:404:10)<br>    at Module.load (module.js:343:32)<br>    at Function.Module._load (module.js:300:12)<br>    at Module.require (module.js:353:17)<br>npm WARN ENOENT ENOENT: no such file or directory, open 'C:\Users\rbasniak\Documents\Visual Studio 2015\Projects\WebApplication4\src\WebApplication4\node_modules\gaze\package.json'<br>npm WARN ENOENT ENOENT: no such file or directory, open 'C:\Users\rbasniak\Documents\Visual Studio 2015\Projects\WebApplication4\src\WebApplication4\node_modules\glob-watcher\package.json'<br>npm WARN ENOENT ENOENT: no such file or directory, open 'C:\Users\rbasniak\Documents\Visual Studio 2015\Projects\WebApplication4\src\WebApplication4\node_modules\glogg\package.json'<br>npm WARN ENOENT ENOENT: no such file or directory, open 'C:\Users\rbasniak\Documents\Visual Studio 2015\Projects\WebApplication4\src\WebApplication4\node_modules\gulplog\package.json'<br>npm WARN ENOENT ENOENT: no such file or directory, open 'C:\Users\rbasniak\Documents\Visual Studio 2015\Projects\WebApplication4\src\WebApplication4\node_modules\has-gulplog\package.json'<br>npm WARN ENOENT ENOENT: no such file or directory, open 'C:\Users\rbasniak\Documents\Visual Studio 2015\Projects\WebApplication4\src\WebApplication4\node_modules\hawk\package.json'<br>npm WARN ENOENT ENOENT: no such file or directory, open 'C:\Users\rbasniak\Documents\Visual Studio 2015\Projects\WebApplication4\src\WebApplication4\node_modules\http-errors\package.json'<br>npm WARN ENOENT ENOENT: no such file or directory, open 'C:\Users\rbasniak\Documents\Visual Studio 2015\Projects\WebApplication4\src\WebApplication4\node_modules\loud-rejection\package.json'<br>npm WARN ENOENT ENOENT: no such file or directory, open 'C:\Users\rbasniak\Documents\Visual Studio 2015\Projects\WebApplication4\src\WebApplication4\node_modules\serve-index\package.json'<br>npm WARN ENOENT ENOENT: no such file or directory, open 'C:\Users\rbasniak\Documents\Visual Studio 2015\Projects\WebApplication4\src\WebApplication4\node_modules\<a href="http://socket.io" rel="nofollow noopener" title="socket.io">socket.io</a>-parser\package.json'<br>npm WARN ENOENT ENOENT: no such file or directory, open 'C:\Users\rbasniak\Documents\Visual Studio 2015\Projects\WebApplication4\src\WebApplication4\node_modules\sparkles\package.json'<br>npm WARN ENOENT ENOENT: no such file or directory, open 'C:\Users\rbasniak\Documents\Visual Studio 2015\Projects\WebApplication4\src\WebApplication4\node_modules\spdx-correct\package.json'<br>npm WARN ENOENT ENOENT: no such file or directory, open 'C:\Users\rbasniak\Documents\Visual Studio 2015\Projects\WebApplication4\src\WebApplication4\node_modules\spdx-exceptions\package.json'<br>npm WARN ENOENT ENOENT: no such file or directory, open 'C:\Users\rbasniak\Documents\Visual Studio 2015\Projects\WebApplication4\src\WebApplication4\node_modules\spdx-expression-parse\package.json'<br>npm WARN ENOENT ENOENT: no such file or directory, open 'C:\Users\rbasniak\Documents\Visual Studio 2015\Projects\WebApplication4\src\WebApplication4\node_modules\spdx-license-ids\package.json'<br>npm WARN ENOENT ENOENT: no such file or directory, open 'C:\Users\rbasniak\Documents\Visual Studio 2015\Projects\WebApplication4\src\WebApplication4\node_modules\statuses\package.json'<br>npm WARN EPACKAGEJSON dotnetpro-ecollector@1.0.0 No description<br>npm WARN EPACKAGEJSON dotnetpro-ecollector@1.0.0 No repository field.<br>npm ERR! Windows_NT 10.0.10586<br>npm ERR! argv "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Web\\External\\node.exe" "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Web\\External\\node_modules\\npm\\bin\\npm-cli.js" "install"<br>npm ERR! node v5.4.1<br>npm ERR! npm  v3.3.4<br>npm ERR! code ELIFECYCLE<br>npm ERR! dotnetpro-ecollector@1.0.0 postinstall: `typings install &amp;&amp; gulp restore`<br>npm ERR! Exit status 1<br>npm ERR! <br>npm ERR! Failed at the dotnetpro-ecollector@1.0.0 postinstall script 'typings install &amp;&amp; gulp restore'.<br>npm ERR! This is most likely a problem with the dotnetpro-ecollector package,<br>npm ERR! not with npm itself.<br>npm ERR! Tell the author that this fails on your system:<br>npm ERR!     typings install &amp;&amp; gulp restore<br>npm ERR! You can get their info via:<br>npm ERR!     npm owner ls dotnetpro-ecollector<br>npm ERR! There is likely additional logging output above.<br>npm ERR! Please include the following file with any support request:<br>npm ERR!     C:\Users\rbasniak\Documents\Visual Studio 2015\Projects\WebApplication4\src\WebApplication4\npm-debug.log</p><p>Do you have any idea of what could be wrong?</p>

**Comment by JuergenGutsch** [comment]
Comment written by Murat Mercan at 15.08.2016 04:57:37:

<p>am I the only one who uses Visual studio to debug typescript, uses breakpoints and step into/over the lines, please let me know if I am doing wrong but without<br>  meta: { '*.js': { scriptLoad: true } } <br>in systemjs.config.js config I am not be able to debug my typescript in Visual studio</p>

**Comment by JuergenGutsch** [comment]
Comment written by John Born at 15.08.2016 23:15:19:

<p>First thing I've checked after hitting this page was the RC version used. I will have a good read if you actually update it to RC5. Many thanks!</p>

**Comment by JuergenGutsch** [comment]
Comment written by Igor Soloydenko at 17.08.2016 01:11:11:

<p>If you have fixed it. Could you please provide a sample of a minimal working solution in GitHub?</p>

**Comment by JuergenGutsch** [comment]
Comment written by MV10 at 17.08.2016 01:19:11:

<p>Fortunately it looks like RC5 should be the final changes.</p>

**Comment by JuergenGutsch** [comment]
Comment written by MV10 at 17.08.2016 01:22:17:

<p>My Core project is already too complicated to easily unwind, but I also set up a bare-bones .NET 4.5.2 VS2015 project and all the important files should be the same. I'll set it up tomorrow and post a link here.</p>
